### ISSUE TITLE
[Bug]Problem that ID is corrected by Javascript

### ISSUE THREAD

**Issue by Takenori-Kusaka** [Erudika/para-cli#1]
Hi,

If the ID of the registered object is all numbers, it is corrected because it exceeds "2 ^ 53 - 1" and can not be handled correctly.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

example:
ID:123456789123456789
command:$para-cli delete --id 123456789123456789
result: Deleted objects [ '123456789123456800' ] from Para.

I support you for your activities.
Best Regards.

**Comment by albogdano** [comment]
Thanks for reporting this @Takenori-Kusaka! I'll get this fixed today.
