### ISSUE TITLE
Can't run para-cli

### ISSUE THREAD

**Issue by TamirErez** [Erudika/para-cli#25]
Hello,
I can't get para-cli to run.
I ran `npm install -g para-cli` which downloaded the files to appdata/roaming/npm
Inside this folder I tried running `para-cli setup` and got the following error:
![image](https://user-images.githubusercontent.com/15075254/170825002-5bb9bb64-05a3-4ec2-9cb3-f724b2b0a2d5.png)
I tried to run this on webstorm and played a bit with the dependencies but still couldn't get past this error
Any help will be appreciated

**Comment by albogdano** [comment]
Perhaps you have an older version of Node.js. Try with the latest 14.x or 16.x
