### ISSUE TITLE
Connection failed with version 1.20.4

### ISSUE THREAD

**Issue by ghost** [Erudika/para-cli#40]
I can't connect to my Para endpoint using v1.20.4 of the para-cli. I've tried against two different Para endpoints I'm running, and both are accessible from the same machine and return the "All set!" response when curl is run against /v1/_setup. Any other pointers for diagnosis? Para version on the backend is 1.48.2.

**Comment by ghost** [comment]
Also to note, there are no issues connecting to the Para endpoint from the associated Scoold apps.

**Comment by albogdano** [comment]
I have not seen any issues like that recently. Try deleting the file `~/.config/para-cli-nodejs/config.json` and run `para-cli setup` again. Also make sure there are no spaces in your secret key.

**Comment by ghost** [comment]
My config file was at  /Users/[username]/Library/Preferences/para-cli-nodejs/config.json and I deleted that and tried running setup again but with no luck.

I tried the above for both a trailing slash and no trailing slash on the endpoint as I know this was a bug in earlier versions, but again, no luck. I checked secret and access keys carefully too.

**Comment by albogdano** [comment]
Are you sure that Para can be accessed at the location you entered for endpoint URL? Check it by opening that URL at path /ping or /v1

**Comment by albogdano** [comment]
@asos-robbell Any progress on this? Are you still having difficulties connecting using para-cli?

**Comment by albogdano** [comment]
I couldn't reproduce this issue - will reopen it when we have more details.
